### ISSUE TITLE
focus_force

### ISSUE THREAD

**Issue by PySimpleGUI** [dchen327/pingmote#13]
I saw one place that directly called tkinter:

```python
    def show_gui(self):
        self.window.un_hide()
        self.window.TKroot.focus_force()  # force window to be focused
        self.hidden = False
```

There's a function in PySimpleGUI to do this for you so you don't have to invoke any tk calls directly.

```python
self.window.force_focus()
```

**Comment by dchen327** [comment]
I believe I tried using `self.window.force_focus()`, but I just get this:
```py
AttributeError: 'Window' object has no attribute 'focus_force'
```
I'm on Python 3.9.1 in Windows with PySimpleGUI 4.38.0 (same issue with 4.34.0).

**Comment by PySimpleGUI** [comment]
Yes, I'm sure you in fact got that error because the `Window` object indeed does not have `focus_force`

The line of code I included in the comment was this one:

```python
self.window.force_focus()
```

Words are flipped in this particular call.

I generally have method names, functions, that follow the format of verb_noun.  Like set_alpha, instead of alpha_set.

In addition to the call reference, which is searchable with a Control+F

https://pysimplegui.readthedocs.io/en/latest/call%20reference/#window

you might find the built-in help to be useful for these kinds of things too.

Call `main_sdk_help()`

Or, you can call `sg.main()` and choose the SDK Reference button

If you click "Summary Only", then you'll get just the list of methods, properties.   There is also an active link at the bottom of this window to the call reference for the object you're looking at.

In the case, of the Window object, note the same link as the one I provided above.  It's just a quick way to get to the same info.  Clicking it will open your browser.

![image](https://user-images.githubusercontent.com/46163555/114284100-84ef4580-9a1b-11eb-8c48-25d4636f4adf.png)


![image](https://user-images.githubusercontent.com/46163555/114284070-570a0100-9a1b-11eb-8eb2-9644cd1eb02b.png)

I hope you don't mind that I posted a Tweet today about your project.  I'm sure other users will find it as inspirational as I have!

https://twitter.com/PySimpleGUI/status/1380957540813524996

**Comment by dchen327** [comment]
Oh I didn't realize the words were flipped! Everything's working now.

I didn't know about `sg.main`; I'll definitely be using that in the future.

Thanks for all the support!

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/114287008-93e0f280-9a31-11eb-9f1f-81fd601d8e4f.png)

Yea, sg.main() has good stuff.

It is where you will be able to soon access the GUII for opening an Issue on GitHub
