### ISSUE TITLE
Two "bad files" when running on 3.6

### ISSUE THREAD

**Issue by PySimpleGUI** [dchen327/pingmote#17]
There are 2 images in the assets that cause problems for tkinter when running Python 3.6.

This is the error message in the PySimpleGUI on GitHub.... the error checking isn't in the released code.  It simply crashes in an ungraceful manner.

![image](https://user-images.githubusercontent.com/46163555/114461751-1ee7f700-9bb0-11eb-9f96-6324530d5980.png)

(BTW, unable to see the buttons in this error window because your code set all buttons, globally, to have the background and text be the same of the background

I've recently learned about 3.6 having this problem with some images. I've found it to be extremely arere as I've used 3.6 since the start of the project.

When I removed these 2 images, the code had no problems running on 3.6.

![crydeath](https://user-images.githubusercontent.com/46163555/114458488-44bfcc80-9bad-11eb-8783-9ba4f41eb44a.png)
![757356443878948944](https://user-images.githubusercontent.com/46163555/114458490-44bfcc80-9bad-11eb-89d2-1d5323742bbe.png)

-----------------------------------

Button colors.... you really only need to set the background color in order for your buttons with images to look OK. If you leave the text alone, then you'll at least be able to see the buttons.

I removed your set_options call and instead used the themes calls to set up the conditions you're wanting.  At least I think I did.

```python
        button_color = sg.theme_button_color()
        sg.theme_background_color(GUI_BG_COLOR)
        sg.theme_text_element_background_color(GUI_BG_COLOR)
        sg.theme_text_color('white')
        sg.theme_button_color((button_color[0], GUI_BG_COLOR))
        sg.theme_border_width(0)
```

This way you'll see the "Close" and "Take me to error" buttons, even though they don't have a shape around them, you know that you can click them.

![image](https://user-images.githubusercontent.com/46163555/114461918-58206700-9bb0-11eb-8dd3-2aa89d69d156.png)

**Comment by dchen327** [comment]
Updated!

**Comment by PySimpleGUI** [comment]
Good man!  

Thanks for writing this great little program.  I use it in all my Discord chats.

![](https://raw.githubusercontent.com/PySimpleGUI/PySimpleGUI/master/images/emojis/thumb_112.png)

**Comment by PySimpleGUI** [comment]
Oooo... that worked too!  I used Pingmote to add the link to the issue... then I simply added a `![]()` where the link goes in the `(  )`
