### ISSUE TITLE
Using the new psgtray package

### ISSUE THREAD

**Issue by PySimpleGUI** [dchen327/pingmote#19]
Hi there.... this is the last message I posed in another issue here.  I thought it would be best if I opened an issue to discuss this specific topic:

------------------------

OK!  As promised, back with more details.

I've changed my version of pingmore to use the newly released psgtray feature.

This system tray icon is for PingMote.  The keyboard shortcuts still work of course.  It's another way to bring up the interface.  A single click of the icon will both bring it up or hide it again.

![image](https://user-images.githubusercontent.com/46163555/122800236-b2186980-d290-11eb-9b33-0eea70eb366d.png)

The code is in my repo:

https://github.com/PySimpleGUI/pingmote

Information about the new package is in the latest announcement and there will be a new issue opened a bit later today to tell everyone more about this feature.  It's not yet in the documentation.

------------------------------

Since posting that message, I have taken the psgtray code and made a package from it that can be installed via pip:

`pip install psgtray`

The code in my repo (link above) has the icon I made for pingmote as well as code that integrates your code with the new psgtray feature.

Clearly this is a program I use on a frequent basis.  Thank you for writing it.

**Comment by dchen327** [comment]
Thank you so much for running away with this program -- you've definitely given me a ton of inspiration for pingmote and future projects. I'll check out the new program as soon as I get a chance! Does the tray feature work on OS X and Linux as well?

**Comment by PySimpleGUI** [comment]
I was able to get it to run on my Linux system, but it sometimes had trouble.  It uses GTK.

I have no clue how it runs on a Mac.  Maybe it'll be ok... maybe not....

For Windows, it's working really well and that's at least 1/2 of the PySimpleGUI users so it's a good start.

**Comment by dchen327** [comment]
Just pulled -- for some reason the GUI no longer shows, gonna look into it now!

**Comment by PySimpleGUI** [comment]
Wait... it's closed?  Did you solve it?  Your last message is that the GUI no longer showed up.  I checked to make sure what I'm running is the same as I uploaded to my repo and it matches.

**Comment by dchen327** [comment]
Yep fixed everything!! All's good and working

**Comment by PySimpleGUI** [comment]
```
MMP"""""""MM                                                           dP 
M' .mmmm  MM                                                           88 
M         `M dP  dP  dP .d8888b. .d8888b. .d8888b. 88d8b.d8b. .d8888b. 88 
M  MMMMM  MM 88  88  88 88ooood8 Y8ooooo. 88'  `88 88'`88'`88 88ooood8 dP 
M  MMMMM  MM 88.88b.88' 88.  ...       88 88.  .88 88  88  88 88.  ...    
M  MMMMM  MM 8888P Y8P  `88888P' `88888P' `88888P' dP  dP  dP `88888P' oo 
MMMMMMMMMMMM
```

Congrats!

I like that the read doesn't have a timeout now so that it won't eat any CPU time, in theory.
